name: open_nizvpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'
version: 1.0.0+1

environment:
  #sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.18.6 <3.0.0"

  

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  csv: ^5.0.2
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_info: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/